varying_param: 'label_noise_std'
L: 2
n: 8000
batch_size: 8000
n_test: 200
batch_size_test: 200
h: 1500
d: 1000
label_noise_std:
  - 0.1
  - 0.3
  - 0.5
  - 0.7
optimizer: 'adam'
momentum: 0
weight_decay: 0
lr: 1
# lr_scheduler_cls: StepLR
# lr_scheduler_kwargs:
#   step_size: 1
#   gamma: 0.4
reg_lambda: 0.01
enable_weight_normalization: false
# NOTE: The probing occurs based on number of steps.
# set appropriate values based on n, batch_size and num_epochs.
num_epochs: 10
probe_freq_steps: 1
# setting this to True will only plot the losses, sim(W, \beta) and KTA.
lightweight: true
probe_weights: false
# set "plot_overlaps": True for plotting the overlaps between singular vectors.
# Note: make sure that "probe_freq_steps": 1 when this is set. The bulk runs
# do not need this so no need to set this to True.
plot_overlaps: false
probe_features: false
fix_last_layer: true
enable_ww: false  # setting `enable_ww` to True will open plots that need to be closed manually.
repeat: 2  # repeat counter for plotting means and std of results.
